
import Pojos.Test

rule "slight case"
    dialect "java"
    when
        op1 :  Test(score < 9)
    then
        System.out.println("Your case seems to be slight");
end

rule "moderate case"
    dialect "java"
    when
        op2 : Test(score > 9 && score < 18)
    then
        System.out.println("Your case seems to moderate you should take some precautions");
end

rule "severe case"
    dialect "java"
    when
        op3 : Test(score > 18)
    then
        System.out.println("Your case seems to be severe you should go to the hospital as sson as possible");
end