/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interfaz;

import Pojos.*;

/**
 *
 * @author andre
 */
public class Test1 extends javax.swing.JPanel {

    /**
     * Creates new form Test1
     */
    public Test1() {
        initComponents();
        if(Principal.test.getQuestion_1() >= 36 && Principal.test.getQuestion_1() <= 37) {
            this.feverValues.setValue(Principal.test.getQuestion_1());
        }
        else if(Principal.test.getQuestion_1() > 37 && Principal.test.getQuestion_1() <= 38) {
            this.feverValues.setValue(Principal.test.getQuestion_1());
        }
        else if(Principal.test.getQuestion_1() > 38 && Principal.test.getQuestion_1() <= 39) {
            this.feverValues.setValue(Principal.test.getQuestion_1());
        }
        else{
            this.feverValues.setValue(Principal.test.getQuestion_1());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        yesNoGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        feverValues = new javax.swing.JSlider();

        setBackground(java.awt.Color.white);
        setForeground(java.awt.Color.black);

        jLabel1.setForeground(java.awt.Color.black);
        jLabel1.setText("Can you specify your temperature?");

        feverValues.setBackground(java.awt.Color.white);
        feverValues.setForeground(java.awt.Color.black);
        feverValues.setMajorTickSpacing(1);
        feverValues.setMaximum(40);
        feverValues.setMinimum(36);
        feverValues.setPaintLabels(true);
        feverValues.setPaintTicks(true);
        feverValues.setValue(36);
        feverValues.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                feverValuesStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(feverValues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(feverValues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void feverValuesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_feverValuesStateChanged
        // TODO add your handling code here:
        Principal.test.setQuestion_1(this.feverValues.getValue());
    }//GEN-LAST:event_feverValuesStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider feverValues;
    private javax.swing.JLabel jLabel1;
    private javax.swing.ButtonGroup yesNoGroup;
    // End of variables declaration//GEN-END:variables
}
